SELECT * FROM hr.employees;
SELECT MAX(SALARY) FROM hr.employees;
SELECT MAX(SALARY) - MIN(SALARY) FROM hr.employees;
SELECT JOB_ID, AVG(SALARY) FROM hr.employees
GROUP BY JOB_ID
ORDER BY AVG(SALARY) DESC;
SELECT SUM(SALARY) FROM hr.employees;
SELECT 
	ROUND(MAX(SALARY), 2),
    ROUND(MIN(SALARY), 2),
    ROUND(AVG(SALARY), 2),
    ROUND(SUM(SALARY), 2)
FROM hr.employees;
SELECT JOB_ID, COUNT(*) AS IT_PROG FROM hr.employees
WHERE JOB_ID = 'IT_PROG';
SELECT JOB_ID, SUM(SALARY) FROM hr.employees
GROUP BY JOB_ID;
SELECT JOB_ID, SUM(SALARY) FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';
SELECT AVG(SALARY) AS Média_salarial, JOB_ID FROM hr.employees
WHERE JOB_ID <> 'IT_PROG'
GROUP BY JOB_ID
ORDER BY Média_salarial DESC;
SET SQL_SAFE_UPDATES = 0;
UPDATE hr.employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777')
WHERE PHONE_NUMBER LIKE '515%';
SELECT * FROM hr.employees
WHERE LENGTH(FIRST_NAME) >= 8;
SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM hr.employees;
SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM hr.employees;
SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM hr.employees;
SELECT UCASE(CONCAT(FIRST_NAME, ' ', LAST_NAME)) FROM hr.employees;
SELECT LAST_NAME, HIRE_DATE FROM hr.employees
WHERE HIRE_DATE LIKE '1987-07%';
SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURRENT_DATE, HIRE_DATE) FROM hr.employees; 