USE hr;
SELECT * FROM locations;

ALTER TABLE locations CHANGE COLUMN STREET_ADDRESS address VARCHAR(40); 

ALTER TABLE regions CHANGE COLUMN REGION_NAME region VARCHAR(25);

ALTER TABLE countries CHANGE COLUMN  COUNTRY_NAME country VARCHAR(25);